version: "3"
services:
  2021-11-15-nhentai-to-pdf:
    container_name: 2021-11-15-nHentai-to-PDF
    image: 9-fs/2021-11-15-nhentai-to-pdf
    environment:
      - HOST_OS=Unraid
      - TZ=UTC
    volumes:
      - /mnt/user/appdata/2021-11-15-nhentai-to-pdf/config/:/app/config/:rw
      - /mnt/user/appdata/2021-11-15-nhentai-to-pdf/log/:/app/log/:rw
      - /mnt/user/media/hentai/:/app/hentai/:rw
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 20G
    user: 99:100
networks: {}
